workflows:
  react-native-workflow:
    name: React Native Workflow
    environment:
      vars:
        NODE_VERSION: 14.17.0
      xcode: latest
      cocoapods: default
      android:
        image: android:latest
        api_level: 30
        build_tools_version: 30.0.3
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install Dependencies
        script: |
          npm install
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease
          cd ..
      - name: Run Tests
        script: |
          npm test
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - junithjunith28@gmail.com
